; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:matouch_esp32s3_40]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
	-DBOARD_HAS_PSRAM
	-DCONFIG_SPIRAM_USE_MALLOC
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_LOOP_STACK_SIZE=16384
lib_deps =
	bblanchon/ArduinoJson@^7.3.0
	https://github.com/ricmoo/QRCode.git
	me-no-dev/ESPAsyncWebServer@^1.2.3
	me-no-dev/AsyncTCP@^1.1.1
	links2004/WebSockets@^2.4.1
	lovyan03/LovyanGFX@1.1.16

[env:matouch_esp32s3_40_v2_demo]
extends = env:matouch_esp32s3_40
build_flags =
	${env:matouch_esp32s3_40.build_flags}
	-DLEMON_V2_DEMO_MODE=1

[env:matouch_esp32s3_40_v2_real]
extends = env:matouch_esp32s3_40
build_flags =
	${env:matouch_esp32s3_40.build_flags}
	-DLEMON_V2_REAL_MODE=1

[env:matouch_esp32s3_40_usdt_mock]
extends = env:matouch_esp32s3_40
build_src_filter =
	+<*>
	-<usdt_lemon_runtime.cpp>
build_flags =
	${env:matouch_esp32s3_40.build_flags}
	-DLEMON_USDT_MOCK_MODE=1

[env:matouch_esp32s3_40_usdt]
extends = env:matouch_esp32s3_40
build_flags =
	${env:matouch_esp32s3_40.build_flags}
	-DLEMON_USDT_MODE=1
