#!/usr/bin/env python3
"""Convert TTF font to Adafruit GFX / LovyanGFX compatible C header.

Usage:
    python ttf_to_gfx.py <input.ttf> <size_pt> <output.h> <font_name>

Example:
    python ttf_to_gfx.py Satoshi-Regular.ttf 12 Satoshi12.h Satoshi12
"""

import sys
import struct
from pathlib import Path

try:
    import freetype
except ImportError:
    print("Install freetype-py: pip install freetype-py")
    sys.exit(1)


def convert_font(ttf_path: str, size_pt: int, output_path: str, font_name: str,
                 first_char: int = 0x20, last_char: int = 0x7E):
    """Convert a TTF font to Adafruit GFX format C header."""

    face = freetype.Face(ttf_path)
    # Set size in 1/64th of points at 141 DPI (Adafruit GFX standard)
    face.set_char_size(size_pt * 64, 0, 141, 0)

    bitmaps = bytearray()
    glyphs = []

    for char_code in range(first_char, last_char + 1):
        face.load_char(chr(char_code), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
        glyph = face.glyph
        bitmap = glyph.bitmap

        w = bitmap.width
        h = bitmap.rows
        x_offset = glyph.bitmap_left
        y_offset = -glyph.bitmap_top  # GFX format: negative = above baseline
        x_advance = glyph.advance.x >> 6  # Convert from 26.6 fixed point

        bitmap_offset = len(bitmaps)

        if w == 0 or h == 0:
            # Space or empty glyph
            glyphs.append((bitmap_offset, 0, 0, x_advance, 0, 1))
            continue

        # Convert FreeType mono bitmap to packed 1-bit format (MSB first)
        # IMPORTANT: Adafruit GFX uses continuous bit packing (NO per-row padding)
        bit_pos = 0
        current_byte = 0

        for row in range(h):
            row_start = row * bitmap.pitch
            for col in range(w):
                byte_index = row_start + (col >> 3)
                bit_index = 7 - (col & 7)

                if byte_index < len(bitmap.buffer):
                    pixel = (bitmap.buffer[byte_index] >> bit_index) & 1
                else:
                    pixel = 0

                current_byte = (current_byte << 1) | pixel
                bit_pos += 1

                if bit_pos == 8:
                    bitmaps.append(current_byte)
                    current_byte = 0
                    bit_pos = 0

        # Pad remaining bits in the last byte of the entire glyph
        if bit_pos > 0:
            current_byte <<= (8 - bit_pos)
            bitmaps.append(current_byte)

        glyphs.append((bitmap_offset, w, h, x_advance, x_offset, y_offset))

    # Calculate yAdvance (line height)
    y_advance = face.size.height >> 6

    # Generate C header
    lines = []
    lines.append(f"/* {font_name}")
    lines.append(f" * Converted from: {Path(ttf_path).name}")
    lines.append(f" * Size: {size_pt}pt at 141 DPI")
    lines.append(f" * Characters: 0x{first_char:02X}-0x{last_char:02X}")
    lines.append(f" * Generated by ttf_to_gfx.py")
    lines.append(f" */")
    lines.append(f"")

    # Bitmap array
    lines.append(f"const uint8_t {font_name}Bitmaps[] PROGMEM = {{")
    for i in range(0, len(bitmaps), 16):
        chunk = bitmaps[i:i+16]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_str},")
    lines.append(f"}};")
    lines.append(f"")

    # Glyph array
    lines.append(f"const GFXglyph {font_name}Glyphs[] PROGMEM = {{")
    for i, (boff, w, h, xadv, xoff, yoff) in enumerate(glyphs):
        char_code = first_char + i
        ch = chr(char_code) if 0x20 < char_code < 0x7F else ' '
        lines.append(f"  {{ {boff:5d}, {w:3d}, {h:3d}, {xadv:3d}, {xoff:3d}, {yoff:3d} }},  // 0x{char_code:02X} '{ch}'")
    lines.append(f"}};")
    lines.append(f"")

    # Font struct
    lines.append(f"const GFXfont {font_name} PROGMEM = {{")
    lines.append(f"  (uint8_t*){font_name}Bitmaps,")
    lines.append(f"  (GFXglyph*){font_name}Glyphs,")
    lines.append(f"  0x{first_char:02X}, 0x{last_char:02X}, {y_advance} }};")
    lines.append(f"")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    bitmap_kb = len(bitmaps) / 1024
    print(f"  {font_name}: {len(bitmaps)} bytes bitmap ({bitmap_kb:.1f} KB), "
          f"{len(glyphs)} glyphs, yAdvance={y_advance}")


if __name__ == "__main__":
    if len(sys.argv) < 5:
        print(f"Usage: {sys.argv[0]} <input.ttf> <size_pt> <output.h> <font_name>")
        sys.exit(1)

    convert_font(sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])
