#pragma once

// Web móvil completa. Sin CDN, fuentes ni recursos remotos: la caja la sirve
// desde PROGMEM aun cuando no hay internet.
static const char PAGINA[] PROGMEM = R"HTML(<!doctype html>
<html lang="es"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0e1011">
<title>Ferced · Tareas</title>
<style>
:root{--canvas:#0e1011;--surface:#171a1b;--raised:#1d2021;--fg:#fff;--fg2:#c4c7c8;--fg3:#919596;--fg4:#686c6d;--line:#292d2e;--danger:#f87171;--success:#34d399;--radius:18px}
*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}
html{background:var(--canvas);color-scheme:dark}
body{margin:0;background:var(--canvas);color:var(--fg);font:16px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;min-height:100vh}
button,input,textarea{font:inherit}button{min-height:44px;cursor:pointer}button:focus-visible,input:focus-visible,textarea:focus-visible{outline:2px solid #26cfc8;outline-offset:2px}
.app{width:min(100%,760px);margin:auto;padding:calc(22px + env(safe-area-inset-top)) 18px calc(80px + env(safe-area-inset-bottom))}
.mast{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:26px}.eyebrow{font-size:11px;letter-spacing:.18em;color:var(--fg3);text-transform:uppercase}.mast h1{font-size:30px;line-height:1.05;letter-spacing:-.04em;margin:7px 0 0}.clock{text-align:right;color:var(--fg3);font-size:13px;padding-top:2px}
.dayline{border-top:1px solid var(--line);padding-top:15px;margin-bottom:22px}.dayhead{display:flex;justify-content:space-between;align-items:baseline}.dayhead strong{font-size:14px}.dayhead span{font:italic 16px Georgia,serif;color:var(--fg2)}.track{height:3px;background:var(--line);margin-top:13px;overflow:hidden}.track i{display:block;height:100%;width:0;background:linear-gradient(90deg,#3fd95a,#26cfc8,#2c97e6);transition:width .25s ease}
.quick{display:grid;grid-template-columns:1fr auto;gap:9px}.field{width:100%;border:1px solid var(--line);background:var(--surface);color:var(--fg);border-radius:13px;padding:13px 14px;min-height:50px}.field::placeholder{color:var(--fg4)}.primary{border:0;background:var(--fg);color:var(--canvas);border-radius:13px;padding:0 18px;font-weight:700}.more{width:100%;border:0;background:none;color:var(--fg3);text-align:left;padding:7px 2px;margin:3px 0 15px}
.filters{display:flex;gap:5px;overflow:auto;padding-bottom:8px;margin:0 -2px 13px}.filter{border:1px solid transparent;background:none;color:var(--fg3);border-radius:999px;padding:7px 13px;white-space:nowrap}.filter.active{color:var(--fg);border-color:var(--line);background:var(--surface)}
.list{display:grid;gap:9px}.task{border:1px solid var(--line);background:var(--surface);border-radius:var(--radius);overflow:hidden}.task.overdue{border-color:#653a3a}.task.done{opacity:.64}.row{display:grid;grid-template-columns:44px 1fr 44px;align-items:start;padding:12px 8px 11px}.check,.fold,.icon{border:0;background:none;color:var(--fg3);padding:0;display:grid;place-items:center}.check span{width:24px;height:24px;border:1.5px solid var(--fg3);border-radius:8px;display:grid;place-items:center}.done .check span{background:var(--fg);border-color:var(--fg);color:var(--canvas)}.bodybtn{border:0;background:none;color:inherit;text-align:left;padding:1px 4px;min-width:0}.title{font-size:16px;font-weight:600;line-height:1.35;overflow-wrap:anywhere}.done .title{text-decoration:line-through;color:var(--fg3)}.meta{display:flex;flex-wrap:wrap;gap:7px;margin-top:6px;color:var(--fg4);font-size:12px}.due.over{color:var(--danger)}.due.today{color:var(--success)}
.details{border-top:1px solid var(--line);padding:14px 16px 13px 56px}.description{white-space:pre-wrap;color:var(--fg2);font-size:14px;margin:0 0 12px;overflow-wrap:anywhere}.sublist{display:grid;gap:4px}.sub{display:grid;grid-template-columns:36px 1fr;align-items:center;min-height:44px}.sub button{border:0;background:none;color:var(--fg3);padding:0}.sub.done span{text-decoration:line-through;color:var(--fg4)}.actions{display:flex;gap:4px;flex-wrap:wrap;margin-top:12px}.action{border:0;background:var(--raised);color:var(--fg3);border-radius:10px;padding:7px 11px;font-size:13px}.action.danger{color:var(--danger)}
.empty{text-align:center;border:1px dashed var(--line);border-radius:var(--radius);padding:42px 20px;color:var(--fg3)}.empty strong{display:block;color:var(--fg);font:italic 23px Georgia,serif;margin-bottom:8px}.status{position:fixed;z-index:20;left:50%;bottom:calc(18px + env(safe-area-inset-bottom));transform:translate(-50%,18px);background:#f3f4f4;color:#111;padding:10px 15px;border-radius:999px;font-size:13px;opacity:0;pointer-events:none;transition:.2s}.status.show{opacity:1;transform:translate(-50%,0)}
.veil{position:fixed;z-index:30;inset:0;background:#000a;display:none;align-items:flex-end}.veil.open{display:flex}.sheet{width:min(100%,760px);max-height:92vh;overflow:auto;margin:0 auto;background:var(--surface);border:1px solid var(--line);border-bottom:0;border-radius:24px 24px 0 0;padding:20px 18px calc(22px + env(safe-area-inset-bottom))}.sheeth{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.sheeth h2{font-size:20px;letter-spacing:-.02em;margin:0}.close{border:0;background:var(--raised);color:var(--fg2);border-radius:50%;width:44px;padding:0}.label{display:block;color:var(--fg3);font-size:12px;letter-spacing:.08em;text-transform:uppercase;margin:16px 2px 7px}.sheet textarea{resize:vertical;min-height:100px}.dates{display:grid;grid-template-columns:1fr 1fr;gap:10px}.subs{display:grid;gap:6px}.edit-sub{display:grid;grid-template-columns:1fr 44px;gap:6px}.subadd{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:7px}.save{width:100%;margin-top:22px;min-height:52px}
@media(max-width:520px){.dates{grid-template-columns:1fr}.mast h1{font-size:28px}.details{padding-left:16px}}
@media (prefers-reduced-motion:reduce){*,*:before,*:after{transition:none!important;scroll-behavior:auto!important}}
</style></head><body>
<main class="app">
  <header class="mast"><div><div class="eyebrow">Ferced / tareas</div><h1>Lo que sigue.</h1></div><div class="clock" id="today"></div></header>
  <section class="dayline" aria-label="Progreso"><div class="dayhead"><strong id="summary">Cargando…</strong><span id="daycopy">un paso a la vez.</span></div><div class="track"><i id="progress"></i></div></section>
  <form class="quick" id="quick"><input class="field" id="quick-title" maxlength="127" autocomplete="off" placeholder="¿Qué hay que hacer?"><button class="primary" type="submit">Agregar</button></form>
  <button class="more" id="new-details" type="button">+ Agregar con fecha, descripción o subtareas</button>
  <nav class="filters" aria-label="Filtrar tareas"><button class="filter active" data-filter="pending">Pendientes</button><button class="filter" data-filter="today">Hoy</button><button class="filter" data-filter="all">Todas</button><button class="filter" data-filter="done">Hechas</button></nav>
  <section class="list" id="list" aria-label="Lista de tareas"></section>
</main>
<div class="status" id="status" aria-live="polite"></div>
<div class="veil" id="veil" role="dialog" aria-modal="true" aria-labelledby="sheet-title">
  <form class="sheet" id="editor"><div class="sheeth"><h2 id="sheet-title">Nueva tarea</h2><button class="close" id="close" type="button" aria-label="Cerrar">×</button></div>
    <label class="label" for="title">Título</label><input class="field" id="title" maxlength="127" required>
    <label class="label" for="description">Descripción</label><textarea class="field" id="description" maxlength="383" placeholder="Contexto, notas, enlaces…"></textarea>
    <div class="dates"><div><label class="label" for="due">Vence</label><input class="field" id="due" type="datetime-local"></div><div><label class="label" for="reminder">Recordatorio</label><input class="field" id="reminder" type="datetime-local"></div></div>
    <label class="label">Subtareas</label><div class="subs" id="subtasks"></div><div class="subadd"><input class="field" id="sub-new" maxlength="95" placeholder="Nueva subtarea"><button class="action" id="sub-add" type="button">Agregar</button></div>
    <button class="primary save" type="submit">Guardar cambios</button>
  </form>
</div>
<script>
var data={items:[],rev:0},filter='pending',editing=false,editingId=0,draftSubs=[];
var list=document.getElementById('list'),statusEl=document.getElementById('status'),veil=document.getElementById('veil');
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function params(o){var p=new URLSearchParams();Object.keys(o||{}).forEach(function(k){if(o[k]!==undefined&&o[k]!==null)p.append(k,o[k])});return p}
function api(path,payload){var options={cache:'no-store'};if(payload){options.method='POST';options.headers={'X-Ferced':'1'};options.body=params(payload)}return fetch(path,options).then(function(r){return r.json().catch(function(){return{error:'respuesta inválida'}}).then(function(j){if(!r.ok)throw new Error(j.error||('Error '+r.status));return j})})}
function accept(next,paint){if(next&&next.items)data=next;if(paint!==false&&!editing)render();return next}
function mutate(path,payload,message){return api(path,payload).then(function(d){accept(d);if(message)toast(message);return d}).catch(fail)}
function fail(e){toast(e.message||'No pude hablar con la caja');throw e}
function toast(t){statusEl.textContent=t;statusEl.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){statusEl.classList.remove('show')},2400)}
function dayBounds(){var n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()).getTime()/1000;return[a,a+86400]}
function dueLabel(epoch){if(!epoch)return'';var b=dayBounds(),d=new Date(epoch*1000),cls='';if(epoch<Date.now()/1000)cls='over';else if(epoch<b[1])cls='today';var text=epoch<b[0]?'Vencida':epoch<b[1]?'Hoy '+d.toLocaleTimeString('es',{hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString('es',{day:'numeric',month:'short'});return'<span class="due '+cls+'">'+esc(text)+'</span>'}
function visible(it){var b=dayBounds();if(filter==='pending')return!it.done;if(filter==='done')return it.done;if(filter==='today')return!it.done&&it.due>=b[0]&&it.due<b[1];return true}
function taskCard(it,index){var done=it.done?' done':'',over=!it.done&&it.due&&it.due<Date.now()/1000?' overdue':'',subs=it.subtasks||[],sd=subs.filter(function(s){return s.done}).length,meta=[];if(it.due)meta.push(dueLabel(it.due));if(subs.length)meta.push('<span>'+sd+'/'+subs.length+' subtareas</span>');if(it.description)meta.push('<span>con descripción</span>');var detail='';if(!it.collapsed){var subhtml=subs.map(function(s){return'<div class="sub '+(s.done?'done':'')+'"><button type="button" onclick="toggleSub('+it.id+','+s.id+','+(!s.done)+')" aria-label="'+(s.done?'Reabrir ':'Completar ')+esc(s.title)+'">'+(s.done?'✓':'○')+'</button><span>'+esc(s.title)+'</span></div>'}).join('');detail='<div class="details">'+(it.description?'<p class="description">'+esc(it.description)+'</p>':'')+'<div class="sublist">'+subhtml+'</div><div class="actions"><button class="action" onclick="openEdit('+it.id+')">Editar</button><button class="action" onclick="moveTask('+it.id+','+(index-1)+')">↑</button><button class="action" onclick="moveTask('+it.id+','+(index+1)+')">↓</button><button class="action danger" onclick="removeTask('+it.id+')">Borrar</button></div></div>'}return'<article class="task'+done+over+'"><div class="row"><button class="check" onclick="toggleTask('+it.id+','+(!it.done)+')" aria-pressed="'+it.done+'" aria-label="'+(it.done?'Reabrir ':'Completar ')+esc(it.title)+'"><span>'+(it.done?'✓':'')+'</span></button><button class="bodybtn" onclick="openEdit('+it.id+')"><div class="title">'+esc(it.title)+'</div><div class="meta">'+meta.join('')+'</div></button><button class="fold" onclick="collapseTask('+it.id+','+(!it.collapsed)+')" aria-label="'+(it.collapsed?'Expandir':'Colapsar')+'">'+(it.collapsed?'⌄':'⌃')+'</button></div>'+detail+'</article>'}
function render(){var items=data.items||[],pending=items.filter(function(x){return!x.done}),done=items.length-pending.length,over=pending.filter(function(x){return x.due&&x.due<Date.now()/1000}).length;document.getElementById('summary').textContent=pending.length+(pending.length===1?' pendiente':' pendientes')+(over?' · '+over+' vencida'+(over>1?'s':''):'');document.getElementById('progress').style.width=(items.length?Math.round(done/items.length*100):0)+'%';var shown=items.filter(visible);list.innerHTML=shown.length?shown.map(function(it){return taskCard(it,items.indexOf(it))}).join(''):'<div class="empty"><strong>nada por acá.</strong>Cambiá el filtro o agregá la próxima tarea.</div>'}
function toggleTask(id,done){mutate('/api/tasks/done',{id:id,done:done})}function toggleSub(taskId,id,done){mutate('/api/subtasks/done',{taskId:taskId,id:id,done:done})}function collapseTask(id,collapsed){mutate('/api/tasks/collapse',{id:id,collapsed:collapsed})}function moveTask(id,position){if(position<0||position>=data.items.length)return;mutate('/api/tasks/move',{id:id,position:position})}
function removeTask(id){var it=data.items.find(function(x){return x.id===id});if(it&&confirm('Borrar “'+it.title+'” y sus subtareas?'))mutate('/api/tasks/delete',{id:id},'Tarea borrada')}
function localValue(epoch){if(!epoch)return'';var d=new Date(epoch*1000),z=d.getTimezoneOffset()*60000;return new Date(d-z).toISOString().slice(0,16)}function epochValue(id){var v=document.getElementById(id).value;return v?Math.floor(new Date(v).getTime()/1000):0}
function openEdit(id){editing=true;editingId=id||0;draftSubs=[];var it=id?data.items.find(function(x){return x.id===id}):null;document.getElementById('sheet-title').textContent=it?'Editar tarea':'Nueva tarea';document.getElementById('title').value=it?it.title:'';document.getElementById('description').value=it?it.description:'';document.getElementById('due').value=it?localValue(it.due):'';document.getElementById('reminder').value=it?localValue(it.reminder):'';veil.classList.add('open');drawEditorSubs();setTimeout(function(){document.getElementById('title').focus()},80)}
function closeEdit(){editing=false;editingId=0;draftSubs=[];veil.classList.remove('open');render()}
function editorItem(){return editingId?data.items.find(function(x){return x.id===editingId}):null}
function drawEditorSubs(){var it=editorItem(),subs=it?(it.subtasks||[]):draftSubs;document.getElementById('subtasks').innerHTML=subs.map(function(s,i){var title=typeof s==='string'?s:s.title,id=typeof s==='string'?i:s.id;return'<div class="edit-sub"><input class="field" value="'+esc(title)+'" readonly><button class="icon" type="button" onclick="removeEditorSub('+id+')" aria-label="Borrar subtarea">×</button></div>'}).join('')}
function removeEditorSub(id){if(editingId){mutate('/api/subtasks/delete',{taskId:editingId,id:id}).then(drawEditorSubs)}else{draftSubs.splice(id,1);drawEditorSubs()}}
document.getElementById('sub-add').onclick=function(){var input=document.getElementById('sub-new'),title=input.value.trim();if(!title)return;input.value='';if(editingId){mutate('/api/subtasks/create',{taskId:editingId,title:title}).then(drawEditorSubs)}else{draftSubs.push(title);drawEditorSubs()}};
document.getElementById('editor').onsubmit=function(e){e.preventDefault();var payload={title:document.getElementById('title').value.trim(),description:document.getElementById('description').value,due:epochValue('due'),reminder:epochValue('reminder')};if(!payload.title)return;if(editingId){payload.id=editingId;api('/api/tasks/update',payload).then(function(d){accept(d,false);closeEdit();toast('Cambios guardados')}).catch(fail)}else{api('/api/tasks/create',payload).then(function(d){accept(d,false);var id=d.created||Math.max.apply(null,data.items.map(function(x){return x.id}));return draftSubs.reduce(function(p,title){return p.then(function(){return api('/api/subtasks/create',{taskId:id,title:title}).then(function(n){accept(n,false)})})},Promise.resolve())}).then(function(){closeEdit();toast('Tarea creada')}).catch(fail)}};
document.getElementById('quick').onsubmit=function(e){e.preventDefault();var input=document.getElementById('quick-title'),title=input.value.trim();if(!title)return;input.value='';mutate('/api/tasks/create',{title:title},'Tarea agregada')};document.getElementById('new-details').onclick=function(){openEdit(0)};document.getElementById('close').onclick=closeEdit;veil.onclick=function(e){if(e.target===veil)closeEdit()};
document.querySelectorAll('.filter').forEach(function(b){b.onclick=function(){filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(function(x){x.classList.toggle('active',x===b)});render()}});
document.getElementById('today').innerHTML=new Date().toLocaleDateString('es',{weekday:'long',day:'numeric',month:'short'}).replace(' de ','<br>');
api('/api/todos').then(accept).catch(fail);setInterval(function(){if (!editing && !document.hidden) api('/api/todos').then(accept).catch(function(){})},5000);
</script></body></html>)HTML";
